robot_NQJ=1
robot_NJ=5
robot_name="fourbar2TE"
robot_NL=4
robot_gVec=1,1,1
robot_NKP=2
robot_KP="l1 l2"
robot_kinconstr_exist=1
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=3
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=3
