robot_NQJ=4
robot_NJ=5
robot_name="fourbarprisOL"
robot_NL=4
robot_gVec=1,1,1
robot_NKP=3
robot_KP="GK GP HP"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=9
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=12
