robot_NQJ=4
robot_NJ=5
robot_name="palh2m1DE"
robot_NL=6
robot_gVec=1,1,1
robot_NKP=6
robot_KP="a2 a3 a4 a5 d1 d5"
robot_kinconstr_exist=1
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=21
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=49
