robot_NQJ=1
robot_NJ=5
robot_name="fourbar1TE"
robot_NL=4
robot_gVec=1,1,1
robot_NKP=4
robot_KP="l1 l2 l3 l4"
robot_kinconstr_exist=1
robot_NKCP=4
robot_KCP="l1 l2 l3 l4"
robot_NMPVFIXB=9
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=9
